/**
 * pdfBuilder.js
 * Opus One Operational Intelligence Platform
 * PDF Executive Report — 4-page assembly using jsPDF + jspdf-autotable
 *
 * Colours are passed safely to jsPDF using RGB arrays.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import {
  fillPageBackground, drawSectionTitle, drawDivider,
  drawKPICard, drawOEETrendChart, drawParetoChart, drawPageFooter,
  C,
} from './pdfHelpers.js';

import {
  generateReportMeta, generateNarrative, generateHighlights,
  generateActions, computeBenchmarks, computePlantHealth,
  computeImprovements,
  oeeTrendData, shiftProductivityComparison, alarmHeatmapData,
} from './reportData.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────
const statusLabel = s => s === 'good' ? 'HEALTHY' : s === 'warning' ? 'MONITOR' : 'CRITICAL';
const statusColor = s => s === 'good' ? C.GREEN   : s === 'warning' ? C.AMBER   : C.RED;

// Safe native jsPDF wrappers for arrays
const sf = (doc, rgb) => doc.setFillColor(rgb[0], rgb[1], rgb[2]);
const st = (doc, rgb) => doc.setTextColor(rgb[0], rgb[1], rgb[2]);

// ─── Main builder ─────────────────────────────────────────────────────────────
export function buildPDF(user) {
  const doc   = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const meta  = generateReportMeta(user);
  let y;

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 1 — Cover + Executive Summary
  // ══════════════════════════════════════════════════════════════════════════
  fillPageBackground(doc, pageW, pageH);

  // ── Cover header block ────────────────────────────────────────────────────
  sf(doc, C.DARK2);
  doc.rect(0, 0, pageW, 58, 'F');
  sf(doc, C.CYAN);
  doc.rect(0, 56.5, pageW, 1.5, 'F');

  // Logo
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  st(doc, C.CYAN);
  doc.text('OPUS ONE', 14, 20);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  st(doc, C.MUTED);
  doc.text('Operational Intelligence Platform', 14, 27);

  // Document type badge (top right)
  sf(doc, C.DARK4);
  doc.rect(pageW - 66, 10, 52, 18, 'F');
  sf(doc, C.CYAN);
  doc.rect(pageW - 66, 10, 52, 1.2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(5.5);
  st(doc, C.MUTED);
  doc.text('DOCUMENT TYPE', pageW - 40, 16, { align: 'center' });
  doc.setFontSize(7);
  st(doc, C.CYAN);
  doc.text('EXECUTIVE INTELLIGENCE REPORT', pageW - 40, 22, { align: 'center' });

  // Title + subtitle
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  st(doc, C.WHITE);
  doc.text('Manufacturing Executive Intelligence Report', 14, 40);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  st(doc, C.MUTED);
  doc.text('Enterprise Operational Performance Review \u2014 Comprehensive Analysis', 14, 48);

  // ── Governance block ─────────────────────────────────────────────────────
  y = 66;
  sf(doc, C.DARK2);
  doc.rect(14, y - 3, pageW - 28, 34, 'F');
  sf(doc, C.CYAN);
  doc.rect(14, y - 3, 2, 34, 'F');

  const metaItems = [
    { label: 'Report ID:',    value: meta.reportId },
    { label: 'Version:',      value: meta.version },
    { label: 'Generated:',    value: meta.generatedAt },
    { label: 'Generated By:', value: `${meta.generatedBy} \u2014 ${meta.role}` },
    { label: 'Organization:', value: meta.organization },
    { label: 'Platform:',     value: meta.platform },
  ];

  metaItems.forEach((item, i) => {
    const col = i < 3 ? 0 : 1;
    const row = i < 3 ? i : i - 3;
    const mx  = 20 + col * 95;
    const my  = y + row * 9.5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.5);
    st(doc, C.MUTED);
    doc.text(item.label, mx, my);
    doc.setFont('helvetica', 'normal');
    st(doc, C.WHITE);
    const v = item.value.length > 34 ? item.value.slice(0, 33) + '\u2026' : item.value;
    doc.text(v, mx + 26, my);
  });

  y = 110;

  // ── Executive Commentary ─────────────────────────────────────────────────
  y = drawSectionTitle(doc, 'EXECUTIVE COMMENTARY', y, pageW);
  const narrative = generateNarrative();
  narrative.forEach((para, idx) => {
    const lines = doc.splitTextToSize(para, pageW - 30);
    doc.setFont('helvetica', idx === 0 ? 'bold' : 'normal');
    doc.setFontSize(7.5);
    st(doc, idx === 0 ? C.WHITE : [210, 225, 245]);
    doc.text(lines, 14, y);
    y += lines.length * 4.6 + 4;
  });

  y = drawDivider(doc, y + 2, pageW);

  // ── Plant Health Overview ────────────────────────────────────────────────
  y = drawSectionTitle(doc, 'PLANT HEALTH OVERVIEW', y, pageW);
  const plants = computePlantHealth();

  plants.forEach(p => {
    const sc = statusColor(p.status);
    sf(doc, C.DARK2);
    doc.rect(14, y - 3, pageW - 28, 10, 'F');
    sf(doc, sc);
    doc.rect(14, y - 3, 2.5, 10, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    st(doc, C.WHITE);
    doc.text(`${p.rankLabel}  ${p.plant}`, 21, y + 3);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    st(doc, sc);
    doc.text(statusLabel(p.status), pageW - 16, y + 3, { align: 'right' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    st(doc, C.MUTED);
    doc.text(
      `OEE: ${p.oee}%  \u00B7  Avail: ${p.avail}%  \u00B7  Downtime: ${p.downtime}h`,
      pageW - 78, y + 3, { align: 'right' },
    );
    y += 13;
  });

  y = drawDivider(doc, y + 1, pageW);

  // ── Key Highlights ───────────────────────────────────────────────────────
  y = drawSectionTitle(doc, 'KEY HIGHLIGHTS', y, pageW);
  generateHighlights().forEach(h => {
    sf(doc, C.CYAN);
    doc.circle(17, y + 1.5, 1.2, 'F');
    const lines = doc.splitTextToSize(h, pageW - 33);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    st(doc, C.WHITE);
    doc.text(lines, 22, y + 2.5);
    y += lines.length * 4.6 + 3.5;
  });

  y = drawDivider(doc, y + 1, pageW);

  // ── Recommended Actions ──────────────────────────────────────────────────
  y = drawSectionTitle(doc, 'RECOMMENDED ACTIONS \u2014 TOP PRIORITY', y, pageW);
  generateActions().slice(0, 3).forEach((a, i) => {
    const pc = a.priority === 'HIGH' ? C.RED : a.priority === 'MEDIUM' ? C.AMBER : C.GREEN;
    sf(doc, C.DARK2);
    doc.rect(14, y - 2, pageW - 28, 16, 'F');
    sf(doc, pc);
    doc.rect(14, y - 2, 2.5, 16, 'F');

    // Priority badge
    sf(doc, pc);
    doc.rect(20, y, 18, 5, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(5.5);
    st(doc, C.DARK);
    doc.text(a.priority, 29, y + 3.5, { align: 'center' });

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    st(doc, C.WHITE);
    doc.text(`${i + 1}. ${a.area}`, 42, y + 3.5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    st(doc, C.MUTED);
    doc.text(`Impact: ${a.impact}`, 42, y + 8);

    const aLines = doc.splitTextToSize(a.action, pageW - 58);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(6.5);
    st(doc, C.SLATE);
    doc.text(aLines[0], 42, y + 13);
    y += 20;
  });

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 2 — KPI Dashboard + Plant Analysis
  // ══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  fillPageBackground(doc, pageW, pageH);
  y = 14;

  y = drawSectionTitle(doc, '1.  EXECUTIVE KPI DASHBOARD \u2014 PERFORMANCE VS. TARGET', y, pageW);

  const benchmarks = computeBenchmarks();
  const totalW = pageW - 28;
  const gap    = 3;
  const cardW  = (totalW - gap * (benchmarks.length - 1)) / benchmarks.length;
  const cardH  = 54;

  benchmarks.forEach((kpi, i) => {
    drawKPICard(doc, 14 + i * (cardW + gap), y, cardW, cardH, kpi);
  });
  y += cardH + 12;

  y = drawSectionTitle(doc, '2.  PLANT PERFORMANCE RANKING', y, pageW);

  autoTable(doc, {
    startY: y,
    head: [['Rank', 'Plant Facility', 'OEE %', 'Avail %', 'Perf %', 'Quality %', 'Downtime', 'Status']],
    body: plants.map(p => [
      p.rankLabel, p.plant, `${p.oee}%`, `${p.avail}%`, `${p.perf}%`, `${p.qual}%`, `${p.downtime}h`, statusLabel(p.status),
    ]),
    theme: 'grid',
    headStyles:         { fillColor: C.DARK4, textColor: C.CYAN, fontStyle: 'bold', fontSize: 7.5 },
    bodyStyles:         { fillColor: C.DARK2, textColor: C.WHITE, fontSize: 7.5 },
    alternateRowStyles: { fillColor: C.DARK3 },
    columnStyles:       { 0: { halign: 'center', fontStyle: 'bold' } },
    margin:             { left: 14, right: 14 },
    didParseCell: data => {
      if (data.section !== 'body') return;
      if (data.column.index === 2) {
        const v = parseFloat(data.cell.raw);
        data.cell.styles.textColor = v >= 80 ? C.GREEN : v >= 70 ? C.AMBER : C.RED;
        data.cell.styles.fontStyle = 'bold';
      }
      if (data.column.index === 7) {
        const v = data.cell.raw;
        data.cell.styles.textColor = v === 'HEALTHY' ? C.GREEN : v === 'MONITOR' ? C.AMBER : C.RED;
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });
  y = doc.lastAutoTable.finalY + 10;

  y = drawSectionTitle(doc, '3.  PLANT HEALTH MATRIX', y, pageW);

  autoTable(doc, {
    startY: y,
    head: [['Plant Facility', 'OEE Status', 'Availability Status', 'Overall Health', 'Recommended Action']],
    body: plants.map(p => [
      p.plant,
      p.oee  >= 80 ? 'On Target'   : p.oee  >= 70 ? 'Below Target' : 'Critical',
      p.avail >= 90 ? 'On Target'   : p.avail >= 85 ? 'Below Target' : 'Critical',
      statusLabel(p.status),
      p.status === 'critical' ? 'Immediate intervention required'
        : p.status === 'warning' ? 'Monitor \u2014 escalate if deteriorating'
        : 'Sustain performance & benchmark',
    ]),
    theme: 'grid',
    headStyles:         { fillColor: C.DARK4, textColor: C.CYAN, fontStyle: 'bold', fontSize: 7.5 },
    bodyStyles:         { fillColor: C.DARK2, textColor: C.WHITE, fontSize: 7.5 },
    alternateRowStyles: { fillColor: C.DARK3 },
    margin:             { left: 14, right: 14 },
    didParseCell: data => {
      if (data.section !== 'body' || data.column.index !== 3) return;
      const v = data.cell.raw;
      data.cell.styles.textColor = v === 'HEALTHY' ? C.GREEN : v === 'MONITOR' ? C.AMBER : C.RED;
      data.cell.styles.fontStyle = 'bold';
    },
  });

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 3 — OEE Trend + Shift Intelligence + Alert Summary
  // ══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  fillPageBackground(doc, pageW, pageH);
  y = 14;

  y = drawSectionTitle(doc, '4.  OEE TREND ANALYSIS \u2014 YEAR TO DATE 2026', y, pageW);

  const monthlyData = oeeTrendData.monthly.filter(d => d.oee != null);
  y = drawOEETrendChart(doc, monthlyData, 14, y, pageW - 28, 80);
  y += 2;

  y = drawSectionTitle(doc, '5.  SHIFT PRODUCTIVITY INTELLIGENCE', y, pageW);

  autoTable(doc, {
    startY: y,
    head: [['Shift', 'Plant A \u2014 Pune', 'Plant B \u2014 Nashik', 'Plant C \u2014 Chennai', 'Plant D \u2014 Ahmedabad', 'Enterprise Avg']],
    body: shiftProductivityComparison.map(s => {
      const avg = ((s.plantA + s.plantB + s.plantC + s.plantD) / 4).toFixed(1);
      return [s.shift, `${s.plantA}%`, `${s.plantB}%`, `${s.plantC}%`, `${s.plantD}%`, `${avg}%`];
    }),
    theme: 'grid',
    headStyles:         { fillColor: C.DARK4, textColor: C.CYAN, fontStyle: 'bold', fontSize: 7.5 },
    bodyStyles:         { fillColor: C.DARK2, textColor: C.WHITE, fontSize: 7.5 },
    alternateRowStyles: { fillColor: C.DARK3 },
    margin:             { left: 14, right: 14 },
    didParseCell: data => {
      if (data.section !== 'body' || data.column.index === 0) return;
      const v = parseFloat(data.cell.raw);
      data.cell.styles.textColor = v >= 88 ? C.GREEN : v >= 80 ? C.AMBER : C.RED;
      data.cell.styles.fontStyle = 'bold';
    },
  });
  y = doc.lastAutoTable.finalY + 10;

  y = drawSectionTitle(doc, '6.  ANDON ALERT FREQUENCY ANALYSIS \u2014 BY PLANT & WEEK', y, pageW);

  autoTable(doc, {
    startY: y,
    head: [['Plant', 'Week 1', 'Week 2', 'Week 3', 'Week 4', 'Monthly Total', 'Alert Trend']],
    body: alarmHeatmapData.map(r => {
      const total = r.W1 + r.W2 + r.W3 + r.W4;
      const trend = r.W4 > r.W1 ? 'Increasing' : r.W4 < r.W1 ? 'Decreasing' : 'Stable';
      return [r.label, r.W1, r.W2, r.W3, r.W4, total, trend];
    }),
    theme: 'grid',
    headStyles:         { fillColor: C.DARK4, textColor: C.CYAN, fontStyle: 'bold', fontSize: 7.5 },
    bodyStyles:         { fillColor: C.DARK2, textColor: C.WHITE, fontSize: 7.5 },
    alternateRowStyles: { fillColor: C.DARK3 },
    margin:             { left: 14, right: 14 },
    didParseCell: data => {
      if (data.section !== 'body') return;
      if (data.column.index >= 1 && data.column.index <= 5) {
        const v = parseInt(data.cell.raw);
        data.cell.styles.textColor = v <= 5 ? C.GREEN : v <= 10 ? C.AMBER : C.RED;
      }
      if (data.column.index === 6) {
        const v = data.cell.raw;
        data.cell.styles.textColor = v === 'Decreasing' ? C.GREEN : v === 'Increasing' ? C.RED : C.MUTED;
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 4 — Downtime Analysis + Improvement Opportunities + Action Tracker
  // ══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  fillPageBackground(doc, pageW, pageH);
  y = 14;

  y = drawSectionTitle(doc, '7.  DOWNTIME PARETO ANALYSIS \u2014 PRODUCTIVITY LOSS CONTRIBUTORS', y, pageW);
  const improvements = computeImprovements();
  y = drawParetoChart(doc, improvements, 14, y, pageW - 28);
  y += 10;

  y = drawSectionTitle(doc, '8.  TOP IMPROVEMENT OPPORTUNITIES \u2014 ESTIMATED OEE RECOVERY POTENTIAL', y, pageW);

  autoTable(doc, {
    startY: y,
    head: [['#', 'Loss Category', 'Hours Lost', 'OEE Impact', 'Potential Recovery', 'Cum. %', 'Primary Location']],
    body: improvements.slice(0, 5).map((o, i) => [
      `#${i + 1}`, o.cause, `${o.hours}h`, o.availabilityImpact,
      `+${o.potentialOEEGain}% OEE`, `${o.cumulativePercent}%`,
      `${o.mostAffectedPlant} \u2014 ${o.primaryContributor}`,
    ]),
    theme: 'grid',
    headStyles:         { fillColor: C.DARK4, textColor: C.CYAN, fontStyle: 'bold', fontSize: 7.5 },
    bodyStyles:         { fillColor: C.DARK2, textColor: C.WHITE, fontSize: 7.5 },
    alternateRowStyles: { fillColor: C.DARK3 },
    columnStyles:       { 0: { halign: 'center', fontStyle: 'bold' }, 4: { fontStyle: 'bold' } },
    margin:             { left: 14, right: 14 },
    didParseCell: data => {
      if (data.section !== 'body') return;
      if (data.column.index === 4) data.cell.styles.textColor = C.GREEN;
      if (data.column.index === 3) data.cell.styles.textColor = C.RED;
    },
  });
  y = doc.lastAutoTable.finalY + 10;

  y = drawSectionTitle(doc, '9.  EXECUTIVE ACTION TRACKER \u2014 PRIORITY MATRIX', y, pageW);

  autoTable(doc, {
    startY: y,
    head: [['Priority', 'Focus Area', 'Scope', 'Business Impact', 'Recommended Action']],
    body: generateActions().map(a => [a.priority, a.area, a.plant, a.impact, a.action]),
    theme: 'grid',
    headStyles:         { fillColor: C.DARK4, textColor: C.CYAN, fontStyle: 'bold', fontSize: 7.5 },
    bodyStyles:         { fillColor: C.DARK2, textColor: C.WHITE, fontSize: 7, lineHeight: 1.4 },
    alternateRowStyles: { fillColor: C.DARK3 },
    columnStyles:       { 0: { cellWidth: 18, halign: 'center', fontStyle: 'bold' }, 4: { cellWidth: 70 } },
    margin:             { left: 14, right: 14 },
    didParseCell: data => {
      if (data.section !== 'body' || data.column.index !== 0) return;
      const v = data.cell.raw;
      data.cell.styles.textColor = v === 'HIGH' ? C.RED : v === 'MEDIUM' ? C.AMBER : C.GREEN;
    },
  });

  // ── Footer on every page ─────────────────────────────────────────────────
  const pageCount = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    drawPageFooter(doc, p, pageCount, meta.generatedAt, pageW);
  }

  doc.save(`OpusOne_Executive_Intelligence_Report_${meta.dateTag}.pdf`);
}
