import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import {
  fillPageBackground, drawSectionTitle, drawPageFooter,
  C, drawKPICard, drawDivider
} from '../pdfHelpers.js';

import {
  generateReportMeta, getSuperAdminReportData
} from '../reportData.js';

const sf = (doc, rgb) => doc.setFillColor(rgb[0], rgb[1], rgb[2]);
const st = (doc, rgb) => doc.setTextColor(rgb[0], rgb[1], rgb[2]);
const statusColor = s => s === 'good' ? C.GREEN : s === 'warning' ? C.AMBER : C.RED;

export function buildSuperAdminPDF(user, context) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const meta = generateReportMeta(user, 'SUPER_ADMIN');
  const data = getSuperAdminReportData(context);
  let y;

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 1 — Cover + Executive Summary
  // ══════════════════════════════════════════════════════════════════════════
  fillPageBackground(doc, pageW, pageH);

  sf(doc, C.DARK2); doc.rect(0, 0, pageW, 58, 'F');
  sf(doc, C.CYAN); doc.rect(0, 56.5, pageW, 1.5, 'F');

  doc.setFont('helvetica', 'bold'); doc.setFontSize(20); st(doc, C.CYAN);
  doc.text('OPUS ONE', 14, 20);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); st(doc, C.MUTED);
  doc.text('Operational Intelligence Platform', 14, 27);

  sf(doc, C.DARK4); doc.rect(pageW - 66, 10, 52, 18, 'F');
  sf(doc, C.CYAN); doc.rect(pageW - 66, 10, 52, 1.2, 'F');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(5.5); st(doc, C.MUTED);
  doc.text('DOCUMENT TYPE', pageW - 40, 16, { align: 'center' });
  doc.setFontSize(7); st(doc, C.CYAN);
  doc.text('GLOBAL ENTERPRISE REPORT', pageW - 40, 22, { align: 'center' });

  doc.setFont('helvetica', 'bold'); doc.setFontSize(14); st(doc, C.WHITE);
  doc.text('Global Enterprise Intelligence Report', 14, 40);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); st(doc, C.MUTED);
  doc.text('Executive Review — Group Level Analysis', 14, 48);

  y = 66;
  sf(doc, C.DARK2); doc.rect(14, y - 3, pageW - 28, 34, 'F');
  sf(doc, C.CYAN); doc.rect(14, y - 3, 2, 34, 'F');

  const metaItems = [
    { label: 'Report ID:', value: meta.reportId },
    { label: 'Version:', value: meta.version },
    { label: 'Generated:', value: meta.generatedAt },
    { label: 'Generated By:', value: `${meta.generatedBy} — ${meta.role}` },
    { label: 'Organization:', value: meta.organization },
    { label: 'Scope:', value: 'Global Group Holdings' },
  ];

  metaItems.forEach((item, i) => {
    const col = i < 3 ? 0 : 1;
    const row = i < 3 ? i : i - 3;
    const mx = 20 + col * 95, my = y + row * 9.5;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(6.5); st(doc, C.MUTED);
    doc.text(item.label, mx, my);
    doc.setFont('helvetica', 'normal'); st(doc, C.WHITE);
    doc.text(item.value, mx + 26, my);
  });

  y = 110;
  y = drawSectionTitle(doc, 'GROUP EXECUTIVE KPI PERFORMANCE', y, pageW);
  const cardW = (pageW - 28 - 3 * 4) / 5;
  data.kpis.forEach((kpi, i) => {
    drawKPICard(doc, 14 + i * (cardW + 3), y, cardW, 54, kpi);
  });
  y += 54 + 12;

  y = drawSectionTitle(doc, 'COMPANY HEALTH RANKING', y, pageW);
  data.companies.forEach(p => {
    const sc = statusColor(p.status);
    sf(doc, C.DARK2); doc.rect(14, y - 3, pageW - 28, 10, 'F');
    sf(doc, sc); doc.rect(14, y - 3, 2.5, 10, 'F');

    doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); st(doc, C.WHITE);
    doc.text(`${p.rankLabel}  ${p.company} (${p.location})`, 21, y + 3);

    doc.setFont('helvetica', 'bold'); doc.setFontSize(7); st(doc, sc);
    doc.text(p.healthLabel, pageW - 16, y + 3, { align: 'right' });

    doc.setFont('helvetica', 'normal'); doc.setFontSize(7); st(doc, C.MUTED);
    doc.text(`OEE: ${p.oee}%  ·  Avail: ${p.avail}%  ·  Downtime: ${p.downtime}h`, pageW - 78, y + 3, { align: 'right' });
    y += 13;
  });

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 2 — Company Comparison & Strategic Risk
  // ══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  fillPageBackground(doc, pageW, pageH);
  y = 14;

  y = drawSectionTitle(doc, '1. COMPANY PERFORMANCE COMPARISON', y, pageW);
  autoTable(doc, {
    startY: y,
    head: [['Rank', 'Company', 'Region', 'OEE %', 'Avail %', 'Perf %', 'Qual %', 'Status']],
    body: data.companies.map(p => [
      p.rankLabel, p.company, p.location, `${p.oee}%`, `${p.avail}%`, `${p.perf}%`, `${p.qual}%`, p.healthLabel
    ]),
    theme: 'grid',
    headStyles: { fillColor: C.DARK4, textColor: C.CYAN, fontStyle: 'bold', fontSize: 7.5 },
    bodyStyles: { fillColor: C.DARK2, textColor: C.WHITE, fontSize: 7.5 },
    alternateRowStyles: { fillColor: C.DARK3 },
    margin: { left: 14, right: 14 },
    didParseCell: d => {
      if (d.section !== 'body') return;
      if (d.column.index === 7) {
        d.cell.styles.textColor = d.cell.raw === 'HEALTHY' ? C.GREEN : d.cell.raw === 'MONITOR' ? C.AMBER : C.RED;
      }
    }
  });
  y = doc.lastAutoTable.finalY + 10;

  y = drawSectionTitle(doc, '2. EXECUTIVE SITUATION REPORT (RISK AREAS)', y, pageW);
  autoTable(doc, {
    startY: y,
    head: [['Severity', 'Target Company', 'Message']],
    body: data.actions.map(a => [a.severity.toUpperCase(), a.targetLabel, a.message]),
    theme: 'grid',
    headStyles: { fillColor: C.DARK4, textColor: C.CYAN, fontStyle: 'bold', fontSize: 7.5 },
    bodyStyles: { fillColor: C.DARK2, textColor: C.WHITE, fontSize: 7.5 },
    alternateRowStyles: { fillColor: C.DARK3 },
    margin: { left: 14, right: 14 },
    didParseCell: d => {
      if (d.section !== 'body') return;
      if (d.column.index === 0) {
        d.cell.styles.textColor = d.cell.raw === 'CRITICAL' ? C.RED : C.AMBER;
      }
    }
  });

  // Footer on every page
  const pageCount = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    drawPageFooter(doc, p, pageCount, meta.generatedAt, pageW);
  }

  doc.save(`OpusOne_Global_Enterprise_Report_${meta.dateTag}.pdf`);
}
